### ISSUE TITLE
PHP examples

### ISSUE THREAD

**Issue by basklu** [PomeloPay/pomelopay-connect#1]
PHP examples are missing for the API. 
Please provide a 10 line PHP file that creates a transaction with a localId.

**Comment by sverraest** [comment]
Hi @basklu 

For PHP we recommend using this package https://github.com/PomeloPay/pomelopay-connect-php

You can easily install it using Composer (https://getcomposer.org/) for autoloading.
Have a look at the README examples, we have added an example that shows how to set your localId.

```php
use PomeloPayConnect\Client;

// Get your API Key and App ID from the "Connect" screen on your merchant dashboard
$client = new Client('apikey', 'appid');

// Currency should be your merchant account currency or the payment would be rejected
$json = [
 "currency" => "EUR",
 "amount" => 1234, // 12.34 EUR,
 "localId" => "INVOICE-2020-0001"
 "redirectUrl" => "https://your.webshop.domain.url/my_order/2020_0001" // Optional redirect after payment completion, the payment portal will redirect to this URL and attach queryParameters to this URL, fully optional
];

$transaction = $client->transactions->create($json);
header('Location: '. $transaction->url); // Go to payment screen on Pomelo Pay
die();
```

**Comment by basklu** [comment]
Hi Simon,

Found out that the readme in the downloaded package contains more examples than the one on GitHub.
Anyway, running the composer and stuff seems to work
When I try your example, I get the the following error:
array (
  'message' => 'Transaction data invalid',
  'code' => 'PP-T-003',
  'extraInfo' => 'Signature is missing or is invalid',
  'statusCode' => 400,
)

Bas

The script I ran is the following (changed the keys for security)

<?php
require "vendor/autoload.php";

use PomeloPayConnect\Client;

$api_key = ‘asdfs………….3456gf';
$app_id = ‘aadfsgasdf-fdsa-4ff4-asfd-adsfadfa987987';
$client = new Client($api_key, $app_id);

// Currency should be your merchant account currency or the payment would be rejected
$json = [
 "provider" => "card", // Payment method enabled for your merchant account such as bcmc, card, card
 "currency" => "EUR",
 "amount" => 1234, // 12.34 EUR,
 "localId" => "INVOICE-2020-0001"
//  "redirectUrl" => "https://your.webshop.domain.url/my_order/2020_0001" // Optional redirect after payment completion, the payment portal will redirect to this URL and attach queryParameters to this URL, fully optional
];

$transaction = $client->transactions->create($json);
header('Location: '. $transaction->url); // Go to payment screen on Pomelo Pay
die();

?>

**Comment by sverraest** [comment]
Hi @basklu 

Which version of the php package are you using? We've just tested with several appId's and apiKey's and we get the expected outcome and results. Could you double check the apiKey (= the long token on the Connect page for your app) and the appId (specified as Application ID).

If you still get an invalid signature I recommend the following steps:

1. Make sure you are on the latest version of the php package (composer update pomelopay/pomelopay-connect-php)
2. Make sure you don't have any linebreaks or other breaking characters when pasting in your API key and App Id
3. Make sure the currency you are passing matches the currency of you merchant account.

If it does not work after the following steps kindly share your app id with developers@pomelopay.com and they will be able to investigate further.

**Comment by sverraest** [comment]
Also, I believe in terms of documentation, please note there are 2 packages

https://github.com/PomeloPay/pomelopay-connect (cross platform API documentation)
https://github.com/PomeloPay/pomelopay-connect-php (PHP package with specific documentation for PHP).

You've raised the issue under the cross platform API package which is not specific to PHP so this repository on GitHub would not have a lot of PHP specific documentation.

For the PHP package documentation and issue tracker please refer to https://github.com/PomeloPay/pomelopay-connect-php

**Comment by basklu** [comment]
Hi Simon,

Thank you very much for your patience with me.
Tried the composer path and made a few stupid mistakes.
At least now it works, but……. when I try the same transaction request twice, it says: “Sorry, this transaction or page is no longer accessible!
This link or page has expired. Please contact the merchant directly if you require further assistance"

I try this snippet in a separate php file:
$client = new Client($api_key, $app_id);

// Currency should be your merchant account currency or the payment would be rejected
$json = [
//  "provider" => "card", // Payment method enabled for your merchant account such as bcmc, card, card
 "currency" => "EUR",
 "amount" => 126, // 12.34 EUR,
 "localId" => "INVOICE-2020-0006",
 "redirectUrl" => "https://klaverkaart.nl" // Optional redirect after payment completion, the payment portal will redirect to this URL and attach queryParameters to this URL, fully optional
];

$transaction = $client->transactions->create($json);
header('Location: '. $transaction->url); // Go to payment screen on Pomelo Pay
die();
“
The first time it works and get a nice Pomelo transaction which I can pay for.
When I reload that same php file, the message is shown.
I tried changing the amount and invoice number, but same message appears.

Regards,

Bas

**Comment by sverraest** [comment]
Hi @basklu This could be related to rate limiting for new accounts but should be resolved. 
Could you try again and let us know if you still have this issue?

**Comment by basklu** [comment]
Yess! Resolved. Reloading the script shows me the same transaction page.
Now I can start embedding this into the website.
Thanks a lot.

**Comment by sverraest** [comment]
Great, will close this for now. 
Feel free to raise a new issue if you need further guidance.
